routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::get('upgrade', function () {return view('pages.upgrade');})->name('upgrade');
	 Route::get('map', function () {return view('pages.maps');})->name('map');
	 Route::get('icons', function () {return view('pages.icons');})->name('icons');
	 Route::get('table-list', function () {return view('pages.tables');})->name('table');
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);

	//Cards
    Route::get('total_accounts', function () {return view('Cards_view.total_accounts');})->name('total_accounts');
    Route::get('total_pam_accounts', function () {return view('Cards_view.total_pam_accounts');})->name('total_pam_accounts');
    Route::get('total_production_servers', function () {return view('Cards_view.total_production_servers');})->name('total_production_servers');
    Route::get('servers_without_pam', function () {return view('Cards_view.servers_without_pam');})->name('servers_without_pam');


    //Sections
    Route::get('section/Infrastructure', function () {return view('Cards_view.total_production_servers');})->name('section/Infrastructure');



    Route::get('NCA_Requiremnts/nca', function () {return view('NCA_Requiremnts.NCA');})->name('nca');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        return view('dashboard');
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileRequest;
use App\Http\Requests\PasswordRequest;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{
    /**
     * Show the form for editing the profile.
     *
     * @return \Illuminate\View\View
     */
    public function edit()
    {
        return view('profile.edit');
    }

    /**
     * Update the profile
     *
     * @param  \App\Http\Requests\ProfileRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ProfileRequest $request)
    {
        if (auth()->user()->id == 1) {
            return back()->withErrors(['not_allow_profile' => __('You are not allowed to change data for a default user.')]);
        }

        auth()->user()->update($request->all());

        return back()->withStatus(__('Profile successfully updated.'));
    }

    /**
     * Change the password
     *
     * @param  \App\Http\Requests\PasswordRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function password(PasswordRequest $request)
    {
        if (auth()->user()->id == 1) {
            return back()->withErrors(['not_allow_password' => __('You are not allowed to change the password for a default user.')]);
        }

        auth()->user()->update(['password' => Hash::make($request->get('password'))]);

        return back()->withPasswordStatus(__('Password successfully updated.'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\Models\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        return view('users.index');
    }
}

resources/views/Cards_view/servers_without_pam.blade.php
@extends('layouts.app')

@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    الادارة
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">محفظة القضاء</a>
                    <a class="dropdown-item" href="#">محفظة التنفيذ</a>
                    <a class="dropdown-item" href="#">محفظة التوثيق</a>
                    <a class="dropdown-item" href="#">محفظة الثروة العقارية</a>
                    <a class="dropdown-item" href="#">التحول الرقمي</a>
                    <a class="dropdown-item" href="#">البنية التحتية</a>
                </div>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    الادارة التابعة
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">محفظة القضاء</a>
                    <a class="dropdown-item" href="#">محفظة التنفيذ</a>
                    <a class="dropdown-item" href="#">محفظة التوثيق</a>
                    <a class="dropdown-item" href="#">محفظة الثروة العقارية</a>
                    <a class="dropdown-item" href="#">التحول الرقمي</a>
                    <a class="dropdown-item" href="#">البنية التحتية</a>
                </div>
            </div>
        </div>
    </div>
    <button id="excelHtml5" class="excelHtml5" style="background-color: #2f9c0a">Export excel</button>
    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="name">id</th>
                <th scope="col" class="sort" data-sort="status">Server</th>
                <th scope="col" class="sort" data-sort="status">environment</th>
                <th scope="col" class="sort" data-sort="status">DR , DMZ , DC</th>
                <th scope="col" class="sort" data-sort="status">Port</th>
                <th scope="col" class="sort" data-sort="status">Qradar</th>
                <th scope="col" class="sort" data-sort="status">PAM</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody class="list">
            <tr>
                <th scope="row">
                    <div class="media align-items-center">
                        <div class="media-body">
                            <span class="name mb-0 text-sm">1</span>
                        </div>
                    </div>
                </th>
                <td class="budget">
                    10.161.118.34
                </td>
                <td>
                      <span class="badge badge-dot mr-4">
                        <span class="status"></span>
                      </span>
                </td>
                <td class="text-right">
                </td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection
@push('js')
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
@endpush

resources/views/Cards_view/total_accounts.blade.php
@extends('layouts.app')

@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
        </div></div>
            <div class="table-responsive">
                <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col" class="sort" data-sort="name">Account Name</th>
                        <th scope="col" class="sort" data-sort="budget">Section</th>
                        <th scope="col" class="sort" data-sort="status">Servers</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody class="list">
                    <tr>
                        <th scope="row">
                            <div class="media align-items-center">
                                <a href="#" class="avatar rounded-circle mr-3">
                                    <img alt="Image placeholder" src="../assets/img/theme/bootstrap.jpg">
                                </a>
                                <div class="media-body">
                                    <span class="name mb-0 text-sm">PAM_Najiz_DC</span>
                                </div>
                            </div>
                        </th>
                        <td class="budget">
                            Najiz
                        </td>
                        <td>
                      <span class="badge badge-dot mr-4">
                        <span class="status">10.161.118.34</span>
                      </span>
                        </td>
                        <td class="text-right">
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            @endsection
            @push('js')
                <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
                <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
    @endpush

resources/views/Cards_view/total_pam_accounts.blade.php
@extends('layouts.app')

@section('content')
    <script src=".../"></script>
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
        </div>
    </div>
    <button id="excelHtml5" class="excelHtml5" style="background-color: #2f9c0a">Export excel</button>
        <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="budget">id</th>
                <th scope="col" class="sort" data-sort="budget">Section</th>
                <th scope="col" class="sort" data-sort="budget">Account Name</th>
                <th scope="col" class="sort" data-sort="status">Total Servers</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody class="list">
            <tr>
                <td class="budget">
                    1
                </td>
                <th scope="row">
                    <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                            <img alt="Image placeholder" src="../assets/img/theme/bootstrap.jpg">
                        </a>
                        <div class="media-body">
                            <span class="name mb-0 text-sm">Najiz</span>
                        </div>
                    </div>
                </th>
                <td>
                      <span class="badge badge-dot mr-4">
                        <span class="status">PAM_Najiz_DC</span>
                      </span>
                </td>
                <td>
                      <span class="badge badge-dot mr-4">
                        <span class="status">10.161.118.34</span>
                      </span>
                </td>
                <td class="text-right">
                </td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection
@push('js')
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
@endpush

resources/views/Cards_view/total_production_servers.blade.php
@extends('layouts.app')

@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    الادارة
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">محفظة القضاء</a>
                    <a class="dropdown-item" href="#">محفظة التنفيذ</a>
                    <a class="dropdown-item" href="#">محفظة التوثيق</a>
                    <a class="dropdown-item" href="#">محفظة الثروة العقارية</a>
                    <a class="dropdown-item" href="#">التحول الرقمي</a>
                    <a class="dropdown-item" href="#">البنية التحتية</a>
                </div>
            </div>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    الادارة التابعة
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="#">محفظة القضاء</a>
                    <a class="dropdown-item" href="#">محفظة التنفيذ</a>
                    <a class="dropdown-item" href="#">محفظة التوثيق</a>
                    <a class="dropdown-item" href="#">محفظة الثروة العقارية</a>
                    <a class="dropdown-item" href="#">التحول الرقمي</a>
                    <a class="dropdown-item" href="#">البنية التحتية</a>
                </div>
            </div>
        </div>
    </div>
    <button id="excelHtml5" class="excelHtml5" style="background-color: #2f9c0a">Export excel</button>
    <div class="table-responsive">
        <table class="table align-items-center table-flush">
            <thead class="thead-light">
            <tr>
                <th scope="col" class="sort" data-sort="budget">id</th>
                <th scope="col" class="sort" data-sort="budget">Section</th>
                <th scope="col" class="sort" data-sort="status">Server</th>
                <th scope="col" class="sort" data-sort="status">Type</th>
                <th scope="col" class="sort" data-sort="status">DMZ , DC , DR</th>
                <th scope="col" class="sort" data-sort="status">Environment</th>
                <th scope="col" class="sort" data-sort="status">Port</th>
                <th scope="col" class="sort" data-sort="status">PAM?</th>
                <th scope="col" class="sort" data-sort="status">Qradar?</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody class="list">
            <tr>
                <td class="budget">
                    1
                </td>
                <th scope="row">
                    <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                            <img alt="Image placeholder" src="../assets/img/theme/bootstrap.jpg">
                        </a>
                        <div class="media-body">
                            <span class="name mb-0 text-sm">Najiz</span>
                        </div>
                    </div>
                </th>
                <td>
                      <span class="badge badge-dot mr-4">
                        <span class="status">10.161.118.34</span>
                      </span>
                </td>
                <td class="text-right">
                </td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection
@push('js')
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.min.js"></script>
    <script src="{{ asset('argon') }}/vendor/chart.js/dist/Chart.extension.js"></script>
@endpush

resources/views/layouts/footers/auth.blade.php
{{--<footer class="footer">--}}
{{--    @include('layouts.footers.nav')--}}
{{--</footer>--}}

resources/views/layouts/footers/guest.blade.php
<footer class="py-5">
    <div class="container">
        @include('layouts.footers.nav')
    </div>
</footer>

resources/views/layouts/footers/nav.blade.php
{{--<div class="row align-items-center justify-content-xl-between">--}}
{{--    <div class="col-xl-6">--}}
{{--        <div class="copyright text-center text-xl-left text-muted">--}}
{{--            &copy; {{ now()->year }} <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a> &amp;--}}
{{--            <a href="https://www.updivision.com" class="font-weight-bold ml-1" target="_blank">Updivision</a>--}}
{{--        </div>--}}
{{--    </div>--}}
{{--    <div class="col-xl-6">--}}
{{--        <ul class="nav nav-footer justify-content-center justify-content-xl-end">--}}
{{--            <li class="nav-item">--}}
{{--                <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>--}}
{{--            </li>--}}
{{--            <li class="nav-item">--}}
{{--                <a href="https://www.updivision.com" class="nav-link" target="_blank">Updivision</a>--}}
{{--            </li>--}}
{{--            <li class="nav-item">--}}
{{--                <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>--}}
{{--            </li>--}}
{{--            <li class="nav-item">--}}
{{--                <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>--}}
{{--            </li>--}}
{{--            <li class="nav-item">--}}
{{--                <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>--}}
{{--            </li>--}}
{{--        </ul>--}}
{{--    </div>--}}
{{--</div>--}}

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main"
                aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/blue.png" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
{{--                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">--}}
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>{{ __('Activity') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>{{ __('Support') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse"
                                data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false"
                                aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
        {{--            <form class="mt-4 mb-3 d-md-none">--}}
        {{--                <div class="input-group input-group-rounded input-group-merge">--}}
        {{--                    <input type="search" class="form-control form-control-rounded form-control-prepended" placeholder="{{ __('Search') }}" aria-label="Search">--}}
        {{--                    <div class="input-group-prepend">--}}
        {{--                        <div class="input-group-text">--}}
        {{--                            <span class="fa fa-search"></span>--}}
        {{--                        </div>--}}
        {{--                    </div>--}}
        {{--                </div>--}}
        {{--            </form>--}}
        <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="#navbar-examples" data-toggle="collapse" role="button"
                       aria-expanded="true" aria-controls="navbar-examples">
                        <i class="fas fa-user" style="color: #f4645f;"></i>
                        <span class="nav-link-text" style="color: #f4645f;">{{ __('Account') }}</span>
                    </a>
                    <div class="collapse show" id="navbar-examples">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item ">
                                <a class="nav-link" href="{{ route('profile.edit') }}">
                                    <i class="fas fa-user" style="color: #f4645f;"></i>
                                    {{ __('User profile') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user.index') }}">
                                    <i class="fas fa-users" style="color: #f4645f;"></i>
                                    {{ __('User Management') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('total_production_servers') }}">
                        <i class="fas fa-server text-blue"></i> {{ __('PRODUCTION SERVERS') }}
                    </a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{{ route('servers_without_pam') }}">
                        <i class="fas fa-server text-orange"></i> {{ __('SERVERS WITHOUT PAM') }}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('total_pam_accounts') }}">
                        <i class="ni ni-bullet-list-67 text-default"></i>
                        <span class="nav-link-text">PAM ACCOUNTS</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('nca') }}">
                        <i class="fas fa-polices"></i> {{ __('NCA Requirements') }}
                    </a>
                </li>
                {{--                                <li class="nav-item mb-5 mr-4 ml-4 pl-1 bg-danger" style="position: absolute; bottom: 0;">--}}
                {{--                                    <a class="nav-link text-white" href="https://www.creative-tim.com/product/argon-dashboard-pro-laravel" target="_blank">--}}
                {{--                                        <i class="ni ni-cloud-download-95"></i> Upgrade to PRO--}}
                {{--                                    </a>--}}
                {{--                                </li>--}}

                {{--                <li class="nav-item">--}}
                {{--                    <a class="nav-link" href="{{ route('icons') }}">--}}
                {{--                        <i class="ni ni-planet text-blue"></i> {{ __('Icons') }}--}}
                {{--                    </a>--}}
                {{--                </li>--}}
                {{--                <li class="nav-item ">--}}
                {{--                    <a class="nav-link" href="{{ route('map') }}">--}}
                {{--                        <i class="ni ni-pin-3 text-orange"></i> {{ __('Maps') }}--}}
                {{--                    </a>--}}
                {{--                </li>--}}
                {{--                <li class="nav-item">--}}
                {{--                    <a class="nav-link" href="{{ route('table') }}">--}}
                {{--                      <i class="ni ni-bullet-list-67 text-default"></i>--}}
                {{--                      <span class="nav-link-text">Tables</span>--}}
                {{--                    </a>--}}
                {{--                </li>--}}
                {{--                <li class="nav-item">--}}
                {{--                    <a class="nav-link" href="#">--}}
                {{--                        <i class="ni ni-circle-08 text-pink"></i> {{ __('Register') }}--}}
                {{--                    </a>--}}
                {{--                </li>--}}
                {{--                <li class="nav-item mb-5 mr-4 ml-4 pl-1 bg-danger" style="position: absolute; bottom: 0;">--}}
                {{--                    <a class="nav-link text-white" href="https://www.creative-tim.com/product/argon-dashboard-pro-laravel" target="_blank">--}}
                {{--                        <i class="ni ni-cloud-download-95"></i> Upgrade to PRO--}}
                {{--                    </a>--}}
                {{--                </li>--}}
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading Saved for later-->
            {{--            <h6 class="navbar-heading text-muted">Documentation</h6>--}}
            {{--            <!-- Navigation -->--}}
            {{--            <ul class="navbar-nav mb-md-3">--}}
            {{--                <li class="nav-item">--}}
            {{--                    <a class="nav-link" href="https://argon-dashboard-laravel.creative-tim.com/docs/getting-started/overview.html">--}}
            {{--                        <i class="ni ni-spaceship"></i> Getting started--}}
            {{--                    </a>--}}
            {{--                </li>--}}
            {{--                <li class="nav-item">--}}
            {{--                    <a class="nav-link" href="https://argon-dashboard-laravel.creative-tim.com/docs/foundation/colors.html">--}}
            {{--                        <i class="ni ni-palette"></i> Foundation--}}
            {{--                    </a>--}}
            {{--                </li>--}}
            {{--                <li class="nav-item">--}}
            {{--                    <a class="nav-link" href="https://argon-dashboard-laravel.creative-tim.com/docs/components/alerts.html">--}}
            {{--                        <i class="ni ni-ui-04"></i> Components--}}
            {{--                    </a>--}}
            {{--                </li>--}}
            {{--            </ul>--}}
        </div>
    </div>
</nav>